RCODE:
    code_601: 'Face Not Found'
    code_602: 'Can Not Recognize Face'
    code_603: 'Can Not Connect Micro-Service'
    code_604: 'Login Failed'
    code_605: 'Login Successful'
    code_606: 'Permission Denied'
    code_607: 'SignatureExpired'
    code_608: 'BadSignature'
    code_609: 'Wrong Input'
    code_610: 'UserName Not Found'
    code_611: 'No Matching Found'
    code_612: 'Mode Not Found'
    code_613: 'Out Of The Range'
    code_701: 'Register Error'
    code_702: 'Encoded Image Error'
    code_703: 'Face Search Error'
    code_704: 'Score Too Slow'
    code_705: 'Database SQL Process Error'
    code_706: 'Data Already In Dataset'
    code_707: 'You Have Nothing To Delete'
    code_801: 'Student Not Found'
    code_900: 'SQL Execute Error'
    code_901: 'A Foreign Key Constraint Fails'
    code_902: 'Incorrect string value'
    code_903: 'SQL Data Exists'
    code_1000: 'Done'
    code_1001: 'Server Got Undetermined Error'
    code_1100: 'Maintaining Time'